kind: Deployment
apiVersion: apps/v1
metadata:
  name: devspace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: devspace-default
        app.kubernetes.io/name: devspace-app
    spec:
      containers:
        - name: default
          image: devspace
